clone:
    git:
        image: plugins/git
        tags: true
pipeline:
    build:
        image: plugins/docker
        repo: datafari/ce_build
        tags:
            - latest
            - "${DRONE_COMMIT_SHA}"
        secrets: [ docker_username, docker_password ]
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    notify:
        image: drillster/drone-email
        from : noreply@github.com
        skip_verify: true
        when:
            status: [ success, failure ]
        secrets: [ email_username, email_password, email_port, email_host, email_recipients ]
    rancher:
        image: peloton/drone-rancher
        url: http://rancher.datafari.com:8080
        service: datafarice
        docker_image: datafari/ce_build
        start_first: false
        confirm: true
        timeout: 18000
        secrets: [ RANCHER_ACCESS_KEY, RANCHER_SECRET_KEY ]
branches: 
  - master
  - release-*
