
sudo: true
install: true
git:
  depth: false
addons:
  apt:
    packages:
    - sshpass
language: java
dist: trusty
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2
  
script:
- travis_wait 30 bash linux/bin/deployment_script.sh

notifications:
  email:
    recipients:
      secure: "W4E0hs7ehZHgSXFE9Op+X/TUphjI5gx/p8YJqyZ13WXUmwBd7qB50Uky+HFK9YTlgwA3dGpC6a1VTFqlyTl35dpLNKHhQKWp+YF2qIjrFXxPbOZy9I9Vw9JybVqYAlfUNoQT2RuAUQc2vWcDlEevpGlESZaIGuvC8G8/YbF1n8IDzIrSoJCqKHDfehZzoHLf00pRl1VgJsB3rQsh+IiRQiaN5KU05ulLC+9lhuWzU6ws3UHbJ14Uahwrn3vOBl10cgO4l2zVCnQPGaLy/ayi2WkKN2v5INvt/1pUpGPkTHYoc5SG+qJKIvxq2XzVoq3GuZYsBYz0Fjm97bng3OKR+DPwosAeD1rkzbt5dempQp3yt1DT6RNYMnum03B69WJkwX215Eh2wW1vWDB4RB/qg9+Bx3U3Ich9DNSjTwLO8avx1Ue9YZjCbMLIp1r4hYok7w2WVGQ74b3T+klP52nh8pLssqdyYtJ4augtbi9sU+1yuHEEfBd6uZz38azuq6guRBezgxG1l/lUpw1PMx6Yc3dxpwVNmXjTRNu32CEOYRqqujNh6um48ZZ4VYAs7biTVeSBPxBAuzWg22Yu3rJ8B15pTsdH3FqXOmDbiv0EJIAaTW1mD8NudbCJ4Xiqx/FfP59Er6L+vjL8Y8pHuxiQE4IgzX9YrECxkCNed21hOYU="
    on_success: change
    on_failure: always 
env:
    global:
    - secure: "ZyGw4vK3YZppuSM6QfpapGwaw5M3xtd4xpIRElitcpNSfub9/YWbWWSg6A43WeWeMlS0C/GLAaRuXpJO69tPxInk+17HMyM3Im1W7VdtgDQ4tOJUwWvRF9DYrBnDl9Cy8/2VLwmV7u4G6gn4yUadgHwLHY9YbiAnoy1gc0DoBp5umcXDmr1nLFBB07BC8kplLbKnHHZu/zz42CawXWLMu8J1ngYTfJ+0GQFOiPfOVSKQ/rP3wyoQ6ta3/Vgso8+sNwkKF+TUogyBZzcgcUZ/4IoQPpXv5qeBYiJgyFuon94rWjPb6TrFgiQAQdFhMd9atBLL4b+O0CTNhEgxuXV4VXPfd9SONKn1ZR+5f7IFmfYCgxt4KkDkzh7Y5qVKYbjIBr+3fHng8ndMWJqHzcon2UNtHqbYWPAaB2zw+oL2f2q1YOAsKpPtZzz0raExBBEsM2dCQ9ahGZ2qryP5CXF9q1Vc+gb9vGSg9AkEGSsvLi7IPG2o+FfI9K1qzoDTgsG9Al7BLK7xYxnuLM6p+TUu1TE7nlC2C41tzBN5U3uIm+6iXHBYRpUlR0utaaoecBulqQF13eSESDhtvnWbMzp8U5ZAdjp3m6NvMDlhX1o4z8PufDu3No6KLDeWnU4z/pk2AgRNS9Von56kG3Nl93i7Sa8nyaY/mJ6MdIAIFUOcMHY="
    - secure: "oo1yvaQ259yGAQxR344nVAYR9YiRjO9HzlUS48NayWC6byCVnHK5obD/Fg2Fnk4Qq6IQtKrZK49vNXFMOvDrjBtQC368jz3/sYhZMsPYpXB8NsQk0Jbs8jSfP3NICh+Cj5z8AUOnCkZhhbTDo8SXgyeakM271h3XdkzAaQ7SW+wtAIPd7GLoaHIWmRGaSPbOU5+3M4U+cURrBAK+2yQnqsH2laRxJJGscFlRKHCMnvlhg7mkI4Cko3Ts8IsUYtaVMfWvoPK7paNwu3VHrKw9TcG+HdkzGalVcCtHffkeRvTk6xTygnFMGqk9ZTkDJB4h1h6zgPfLI3iU1HcIzAEgly24jlRxAii2ZFHqLGS7Topp5tYuECLhe6F1zwJto0C0UHqdp+yIPSO5EVyld7QawyGW4fdwSN7C0mxSy75DMlZilpaPCZU7iFWNXjhYF+pTZ93dJsjjF12Rf5uVXMySDvZSqSLBjzDRrObhQR9a+KBwyv6UN3XXE+3rkOp3SXKHaq8Qd3Qr2lwKb/yIrujy15+2C/DGh0f8u1gQ+X2B4iWEVyoP+fhuU64eDm7ls3ojBJUtXGHU3mGF+auVeylDl6rNXrceSeuVcfS1sZPE6Kv4olZjk5EKJ5opDNZMYbte+n1M878DYeMANscIUvgB0yQR+BUz+Zbkg3c7fRWEYF8="
    - secure: "pBDbGTI1AZwsJ9xi6fPasg+rU44xNSP3bi/C8ZbfipfMQ3Pr8juAoXz0SUuBev12+oLjV/PDZHFJArEEgZmBQB39rAJUfW87mfdSU/UZiyL3ORdv1NIk8SeMionhsJOA1Yf8Lt1ocKvE2ojow6gQOdGKmW8U54zdorL+XmxiqkxBDDVeXyQJe9OVgaosjg6nFID1eR9tMI07Ejx6rUvV784YJy5kVOGnzyjQ/RD8ES9g3tFGciig8NGl6Kk1EKgF1bMDIU7psMnG97WToBkXYFEedPwvS+jkI94rdTfifxDU2hRECc8LlC0Q6xBVJZ/XvBqzxkMeePz6aNiSnLJqL156utr1KYEewtuAVEm3OUXUYVxKUy4XLWgNRruQB96y/6HxpSM/98A8xf6F/w+doABTiJ/EtmFEiYYWX9/wbYiYfD0kgCeeowwDpzfVJNIRaPVCHTtKfx4S3xEWc+zKFNNqB8rUUy2HeSuV72U+IZ+FTrOpM6/ebSFQEfpoxMxWfRbyuKalD2tzqgiDALYcVbvhJdBOQkG9q7iw/eTTtlhlSo/ov2SMTj3jyECPdCW0xgkrQCdp3p1amTrf8la53EFK+Caxd3L2iDke2QlfZRrLDe3OQ+riNB0Gw+7RDNLFC31hiZ51QQr7wDBMMVUPZsKNk9HxLlPfyg0e40D1jrE="
    - secure: "lRyXg58XFn5ATH79l6Fa9bWGVRE/MaC78NjVyjVFHnPhTEFTwia2cFnkym3dbR5y1h4dhiib03FeFJH+I7tiFul9on1pEj4PstAeg9FydK12PctiFfLcvbbQsd8Bn9lL0i25Ew60pET1uWINjYpYiop2nTVuLlrGmzUzxQssAp5qRr/aNOGp4Ui0icExxM71ArsNgg7BIhqkSPbEXS69pioJAfwj1zrXtOYioxiIbOgMlxJtqIt4kra2HqcRpQYaNoUwjrbY4xUUDaUdO3GpNmc2S1PtxyRTNVkMe9sBcP858rgzPE5M9snPciN7VPyMB/hxLZCJAVnDirQh5O7ly9OxsD6UFBwrm2XTovJf9NdcR7wvg7GOiAszSFjOrou9UdOcQndKeLmP/qWzswJzfr1yZDFBuWVJ9ZkQ9I9phcbfh0d3ML7833o6JQr+d3q843FP63Twdax5lnUhUhz3QXrajYUJqKX/Lq/ZkRsNbpHed9z8t0xNUXQORi0DxN/TraWieP48Ak4J2tfnkrFUqN4ck+fKUTZ+ZgKA+bFIB0tlgcw8Wto55a7B2FQo89DbM2BWEnLfzFmukEfuL4wzkpiAAOvX5MxTw+aUZd4OMxes5BvlDlVzl9thnct7u+ta7I6RW7A6MPo3PKmlAtkTrrBJWr7MSXvwc5do39HQNpQ="
after_success:
- export SSHPASS=$DEPLOY_PASSWORD
- export ESCAPEDBRANCH=${TRAVIS_BRANCH//\//\\\\}
- sshpass -e scp -o stricthostkeychecking=no linux/installer/dist/datafari.deb $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATHSCRIPT/datafari_community_$ESCAPEDBRANCH.deb

