sudo: false
install: true
env:
  matrix:
    - TEST_SCRIPT="mvn clean install"
    
script: $TEST_SCRIPT
language: java
dist : precise
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
notifications:
  email: false
